language: emacs-lisp
sudo: required
env:
  - EMACS=emacs24
  - EMACS=emacs25
install:
  - sudo add-apt-repository -y ppa:ubuntu-elisp
  - sudo apt-get update -y
  - sudo apt-get install emacs24 emacs25
  - sudo apt-get install gforth || true
script: make EMACS=$EMACS
notifications:
  email: lars@nocrew.org
